spring.application.name=Backend-TVCanaria

# posibles valores: none,validate(valida si esta todo correcto),update(lee entidades y actualiza en funcion de la base de datos),create-drop(cuando arranca crea la estructura de la bbd, y cuando termina se elimina la bbdd)
spring.jpa.hibernate.ddl-auto=update

# Mysql DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/blog_db?serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=usuarioexterno
spring.datasource.password=Toor.toor1

spring.security.user.name=admin
spring.security.user.password=admin

# JWT Configuration
# Cambiar y ocultar en produccion
jwt.secret=r/4pNyeUh2HyVD0nmN8jggMhYKhMA6BKllqjCWN8lXU7hrVvlpiw7mPQ3vo3P013BgPOSg3qWwklYXcfF4+qcQ==
jwt.expiration=86400000

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=58805099479-cpdj03l474rst88ddrtfrb8vhsd5sc93.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

#Cloudinary

cloudinary.cloud_name=dldiqcsrh
cloudinary.api_key=376976238898751
cloudinary.api_secret=EQSbJxJdZtBRPvHFprnWJ9SNMmc

# H2 DB Config
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver

# JPA Config
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

# Tamaño máximo de un solo archivo
spring.servlet.multipart.max-file-size=50MB

# Tamaño máximo de la petición completa (varios archivos)
spring.servlet.multipart.max-request-size=50MB


# Server Config
server.port=8082

