INSERT INTO category(category_id, name) VALUES ('1','Política');
INSERT INTO category(category_id, name) VALUES ('2','Sociedad');
INSERT INTO category(category_id, name) VALUES ('3','Economía');
INSERT INTO category(category_id, name) VALUES ('4','Deportes');
INSERT INTO category(category_id, name) VALUES ('5','Cultura');
INSERT INTO category(category_id, name) VALUES ('6','Tecnología');
INSERT INTO category(category_id, name) VALUES ('7','Ciencia');
INSERT INTO category(category_id, name) VALUES ('8','Salud');
INSERT INTO category(category_id, name) VALUES ('9','Educación');
INSERT INTO category(category_id, name) VALUES ('10','Medio ambiente');
INSERT INTO category(category_id, name) VALUES ('11','Ocio');
INSERT INTO category(category_id, name) VALUES ('12','Turismo');
INSERT INTO category(category_id, name) VALUES ('13','Opinión');
INSERT INTO category(category_id, name) VALUES ('14','Internacional');
INSERT INTO category(category_id, name) VALUES ('15','Local');
INSERT INTO category(category_id, name) VALUES ('16','Economía regional');
INSERT INTO category(category_id, name) VALUES ('17','Empleo');
INSERT INTO category(category_id, name) VALUES ('18','Innovación');
INSERT INTO category(category_id, name) VALUES ('19','Medios de comunicación');
INSERT INTO category(category_id, name) VALUES ('20','Gastronomía');